[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "SalesCrMemoHeader114_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared SalesCrMemoHeader114 = let
  Source = Excel.Workbook(Web.Contents("https://www.dropbox.com/scl/fi/fl91oiquv6a71wrzfxsya/Req-3-Sample-data.xlsx?rlkey=74wh609g7pc5d79kccegid4th&st=xv3fjj3g&dl=1"), null, true),
  #"Navigation 1" = Source{[Item = "SalesCrMemoHeader114", Kind = "Sheet"]}[Data],
  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"TaxExemptionNo-10015", type text}, {"YourReference-11", type text}, {"WCSAL34SampleReasonCode-50050", type text}, {"ShiptoAddress2-16", type text}, {"BilltoName2-6", type text}, {"SelltoCustomerName2-80", type text}, {"WTBALastEmailSentDateTime-87350", type datetime}, {"ShiptoContact-18", type text}, {"CustomerDiscGroup-40", type text}, {"BilltoAddress2-8", type text}, {"SelltoAddress2-82", type text}, {"ShortcutDimension1Code-29", type text}, {"ShiptoCode-12", type text}, {"PaymentMethodCode-104", type text}, {"ReturnOrderNo-6601", type text}, {"ReturnOrderNoSeries-6602", type text}, {"WCINT04PAOrderNo-50650", type text}, {"WCINT04PASalesRep-50651", type text}, {"RcvdfromCountRegionCode-181", type text}, {"AppliestoDocNo-53", type text}, {"ShippingAgentCode-105", type text}, {"SelltoCountryRegionCode-90", type text}, {"VATCountryRegionCode-78", type text}, {"BilltoCountryRegionCode-87", type text}, {"PreAssignedNo-111", type text}, {"PreAssignedNoSeries-107", type text}, {"WTUSBeverageTaxAreaCode-88400", type text}, {"SelltoEMail-172", type text}, {"BilltoContactNo-5053", type text}, {"SelltoContactNo-5052", type text}, {"BilltoContact-10", type text}, {"SelltoContact-84", type text}, {"ShiptoCountryRegionCode-93", type text}, {"SelltoPhoneNo-171", type text}, {"ShiptoAddress-15", type text}, {"ShiptoCity-17", type text}, {"ShiptoCounty-92", type text}, {"ShiptoPostCode-91", Int64.Type}, {"WTBACreditClassCode-87109", type text}, {"BilltoAddress-7", type text}, {"SelltoAddress-81", type text}, {"ShipmentMethodCode-27", type text}, {"BilltoPostCode-85", Int64.Type}, {"SelltoPostCode-88", Int64.Type}, {"SalespersonCode-43", type text}, {"LocationCode-28", type text}, {"PaymentTermsCode-23", type text}, {"ShiptoName-13", type text}, {"BilltoCity-9", type text}, {"SelltoCity-83", type text}, {"$Company", type text}, {"$DeliveredDateTime", type datetime}, {"AllowLineDisc-7001", Int64.Type}, {"AltGenBusPostingGroup-167", Int64.Type}, {"AltVATBusPostingGroup-168", Int64.Type}, {"AltVATRegistrationNo-166", Int64.Type}, {"AppliestoDocType-52", type text}, {"BalAccountType-94", type text}, {"BilltoCounty-86", type text}, {"BilltoCustomerNo-4", type text}, {"BilltoName-5", type text}, {"ContractDetailOverview-8052", type text}, {"Correction-98", Int64.Type}, {"CurrencyFactor-33", Int64.Type}, {"CustLedgerEntryNo-1304", Int64.Type}, {"CustomerPostingGroup-31", type text}, {"CustomerPriceGroup-34", type text}, {"DimensionSetID-480", Int64.Type}, {"DocumentDate-99", Int64.Type}, {"DocumentExchangeStatus-711", type text}, {"DraftCrMemoSystemId-8001", type text}, {"DueDate-24", Int64.Type}, {"EU3PartyTrade-75", Int64.Type}, {"ElectronicDocumentSent-10019", Int64.Type}, {"ElectronicDocumentStatus-10030", type text}, {"ExchangeRateUSD-10060", Int64.Type}, {"ForeignTrade-10050", Int64.Type}, {"GenBusPostingGroup-74", type text}, {"GetReturnReceiptUsed-7200", Int64.Type}, {"InvoiceDiscCode-37", type text}, {"MarkedasCanceled-27008", Int64.Type}, {"No-3", type text}, {"NoPrinted-47", Int64.Type}, {"NoSeries-108", type text}, {"NoofEDocumentsSent-10021", Int64.Type}, {"PaymentDiscount-25", Int64.Type}, {"PostingDate-20", Int64.Type}, {"PostingDescription-22", type text}, {"PrepaymentCreditMemo-136", Int64.Type}, {"PriceCalculationMethod-7000", type text}, {"PricesIncludingVAT-35", Int64.Type}, {"RecurringBilling-8051", Int64.Type}, {"SATAddressID-27009", Int64.Type}, {"SelltoCounty-89", type text}, {"SelltoCustomerName-79", type text}, {"SelltoCustomerNo-2", type text}, {"SourceCode-113", type text}, {"SystemCreatedAt-2000000001", type datetime}, {"SystemCreatedBy-2000000002", type text}, {"SystemModifiedAt-2000000003", type datetime}, {"TaxLiable-115", Int64.Type}, {"UserID-112", type text}, {"VATBaseDiscount-119", Int64.Type}, {"VATReportingDate-179", Int64.Type}, {"WCAR06SalesCommClosed-50101", Int64.Type}, {"WCAR06SalesCommissionable-50100", Int64.Type}, {"WTBABillHoldType-87570", type text}, {"WTBAOrderTypeCode-87007", type text}, {"WTBASOReviewStatus-87851", type text}, {"WTBASalesRegionCode-87003", type text}, {"WTBASampleOrder-87008", Int64.Type}, {"WTBASiteOrderID-87401", Int64.Type}, {"systemId-2000000000", type text}, {"timestamp-0", Int64.Type}, {"InsertDate", type datetime}, {"WTBACoopCode-87650", Int64.Type}, {"ShipmentDate-21", Int64.Type}, {"ExternalDocumentNo-100", type text}, {"VATRegistrationNo-70", type text}, {"UpdateDate", type datetime}}),
  #"Removed columns" = Table.RemoveColumns(#"Changed column type", {"Column121", "Column122"}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Removed columns", {{"DocumentDate-99", type date}, {"DueDate-24", type datetime}, {"PostingDate-20", type datetime}, {"VATReportingDate-179", type datetime}, {"ShipmentDate-21", type date}}),
  #"Removed blank rows" = Table.SelectRows(#"Changed column type 1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
in
  #"Removed blank rows";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "SalesCrMemoLine115_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared SalesCrMemoLine115 = let
  Source = Excel.Workbook(Web.Contents("https://www.dropbox.com/scl/fi/fl91oiquv6a71wrzfxsya/Req-3-Sample-data.xlsx?rlkey=74wh609g7pc5d79kccegid4th&st=xv3fjj3g&dl=1"), null, true),
  #"Navigation 1" = Source{[Item = "SalesCrMemoLine115", Kind = "Sheet"]}[Data],
  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"WCSAL04PalletDiscGroupCode-50121", type text}, {"BinCode-5403", type text}, {"WTBAOrderChargeCode-87600", type text}, {"WTBASampleReasonCode-87700", type text}, {"WCSAL04SampleDiscGroupCode-50120", type text}, {"CustomerDiscGroup-7002", type text}, {"ShortcutDimension1Code-40", type text}, {"WTPCSalesPriceGroupCode-89200", type text}, {"WTPCSalesPriceCategoryCode-89203", type text}, {"ReturnReasonCode-6608", type text}, {"OrderNo-65", type text}, {"WTUSBeverageTaxAreaCode-88400", type text}, {"ItemCategoryCode-5709", type text}, {"PostingGroup-8", type text}, {"WTBABrandNo-87150", type text}, {"WTBAAlcoholTypeCode-87050", type text}, {"WTBABottleSize-87020", type text}, {"UnitofMeasure-13", type text}, {"UnitofMeasureCode-5407", type text}, {"GenProdPostingGroup-75", type text}, {"WCTEWSalespersonCode-50000", type text}, {"WTBABudgetSalespersonCode-87702", type text}, {"GenBusPostingGroup-74", type text}, {"BilltoCustomerNo-68", type text}, {"CustomerPriceGroup-42", type text}, {"SelltoCustomerNo-2", type text}, {"LocationCode-7", type text}, {"Description-11", type text}, {"PostingDate-131", type datetime}, {"$Company", type text}, {"$DeliveredDateTime", type datetime}, {"Amount-29", type number}, {"ApplfromItemEntry-5811", Int64.Type}, {"BlanketOrderLineNo-98", Int64.Type}, {"DepruntilFAPostingDate-5605", Int64.Type}, {"DimensionSetID-480", Int64.Type}, {"DocumentNo-3", type text}, {"GrossWeight-34", Int64.Type}, {"ICPartnerRefType-107", type text}, {"InvDiscountAmount-69", Int64.Type}, {"ItemReferenceType-5727", type text}, {"JobContractEntryNo-1002", Int64.Type}, {"LineNo-4", Int64.Type}, {"NetWeight-35", Int64.Type}, {"OrderLineNo-66", Int64.Type}, {"PmtDiscountAmount-145", Int64.Type}, {"PriceCalculationMethod-7000", type text}, {"Quantity-15", type number}, {"RetentionAttachedtoLineNo-10001", Int64.Type}, {"UnitsperParcel-36", Int64.Type}, {"VAT-25", Int64.Type}, {"VATBaseAmount-99", type number}, {"VATCalculationType-77", type text}, {"WCAR06ManualCommAmount-50112", Int64.Type}, {"WCAR06MaxComm-50113", Int64.Type}, {"WCAR06SalesCommClosed-50101", Int64.Type}, {"WCAR06SalesCommLedgEntry-50102", Int64.Type}, {"WCINT01ShortShipped-50220", Int64.Type}, {"WTBABillHoldEntryNo-87570", Int64.Type}, {"WTBACasePack-87010", Int64.Type}, {"WTBAGrossWeight-87823", Int64.Type}, {"WTBALineDiscAmountBottle-87042", type number}, {"WTBALineDiscAmountCase-87041", type number}, {"WTBALineDiscountUnitAmount-87040", type number}, {"WTBALinkedLineNo-87000", Int64.Type}, {"WTBALiters-87300", type number}, {"WTBAOriginalQtyBottle-87343", Int64.Type}, {"WTBAOriginalQtyCase-87342", type number}, {"WTBAOriginalQuantity-87340", type number}, {"WTBAOriginalQuantityBase-87341", type number}, {"WTBASampleTotalAmount-87701", type number}, {"WTBAVolume-87824", type number}, {"WTCBBillBack-89050", Int64.Type}, {"WTCBChargebackLedgerEntry-89040", Int64.Type}, {"WTCBDeplAllowLineAmt-89030", Int64.Type}, {"WTCBDeplAllowUnitAmtType-89000", type text}, {"WTPCSalesPriceCalcMethod-89201", type text}, {"WTPCSalesPriceLinkId-89204", Int64.Type}, {"WTUSBeverageTax-88401", Int64.Type}, {"AllowInvoiceDisc-32", Int64.Type}, {"AllowLineDisc-7001", Int64.Type}, {"AmountIncludingVAT-30", type number}, {"AppltoItemEntry-38", Int64.Type}, {"AttachedtoLineNo-80", Int64.Type}, {"ContractLineNo-8052", type text}, {"LineAmount-103", type number}, {"LineDiscount-27", Int64.Type}, {"LineDiscountAmount-28", type number}, {"LineDiscountCalculation-180", type text}, {"Nonstock-5710", Int64.Type}, {"PrepaymentLine-123", Int64.Type}, {"QtyperUnitofMeasure-5404", type number}, {"QuantityBase-5415", type number}, {"RetentionVAT-10002", Int64.Type}, {"ReturnReceiptLineNo-6601", Int64.Type}, {"SystemCreatedAt-2000000001", type datetime}, {"SystemCreatedBy-2000000002", type text}, {"SystemCreatedEntry-101", Int64.Type}, {"SystemModifiedAt-2000000003", type datetime}, {"TaxLiable-86", Int64.Type}, {"Type-5", type text}, {"UnitCost-100", type number}, {"UnitCostLCY-23", type number}, {"UnitPrice-22", type number}, {"UnitVolume-37", type number}, {"UseDuplicationList-5613", Int64.Type}, {"VATDifference-104", Int64.Type}, {"WCAR06DefaultComm-50114", Int64.Type}, {"WCAR06DefaultCommAmount-50115", type number}, {"WCAR06ManualComm-50111", Int64.Type}, {"WCAR06SalesCommissionable-50100", Int64.Type}, {"WCINT01ShortShipOrigQty-50221", Int64.Type}, {"WTBAGallons-87301", type number}, {"WTBANetWeight-87870", Int64.Type}, {"WTBAQuantityBottle-87083", Int64.Type}, {"WTBAQuantityCase-87080", type number}, {"WTBAQuantityPallet-87880", type number}, {"WTBASalesPriceOverride-87030", Int64.Type}, {"WTBASampleEntryNo-87704", Int64.Type}, {"WTCBDeplAllowLineUnitAmt-89020", Int64.Type}, {"WTCBDeplAllowUnitAmt-89010", Int64.Type}, {"WTPCSalesPriceCalcQty-89202", type number}, {"systemId-2000000000", type text}, {"timestamp-0", Int64.Type}, {"InsertDate", type datetime}, {"UpdateDate", type datetime}, {"No-6", type text}, {"ShipmentDate-10", type date}, {"WTBADocumentDate-87100", type date}})
in
  #"Changed column type";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "SalesInvoiceHeader112_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared SalesInvoiceHeader112 = let
  Source = Excel.Workbook(Web.Contents("https://www.dropbox.com/scl/fi/fl91oiquv6a71wrzfxsya/Req-3-Sample-data.xlsx?rlkey=74wh609g7pc5d79kccegid4th&st=xv3fjj3g&dl=1"), null, true),
  #"Navigation 1" = Source{[Item = "SalesInvoiceHeader112", Kind = "Sheet"]}[Data],
  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ShiptoName2-14", type text}, {"CustomerDiscGroup-40", type text}, {"BilltoName2-6", type text}, {"SelltoCustomerName2-80", type text}, {"WTBACoopCode-87650", type text}, {"ShiptoAddress2-16", type text}, {"BilltoAddress2-8", type text}, {"SelltoAddress2-82", type text}, {"ShortcutDimension1Code-29", type text}, {"ShiptoCode-12", type text}, {"PaymentMethodCode-104", type text}, {"BilltoCountryRegionCode-87", type text}, {"WTPCPriceCalculatedDate-89201", type datetime}, {"ShiptoContact-18", type text}, {"WTUSBeverageTaxAreaCode-88400", type text}, {"BilltoContact-10", type text}, {"SelltoContact-84", type text}, {"BilltoContactNo-5053", type text}, {"SelltoContactNo-5052", type text}, {"BilltoAddress-7", type text}, {"SelltoAddress-81", type text}, {"OrderNo-44", type text}, {"ShippingAgentCode-105", type text}, {"ShipmentMethodCode-27", type text}, {"ShiptoAddress-15", type text}, {"BilltoPostCode-85", Int64.Type}, {"SelltoPostCode-88", Int64.Type}, {"ShiptoPostCode-91", Int64.Type}, {"PaymentTermsCode-23", type text}, {"BilltoCity-9", type text}, {"SelltoCity-83", type text}, {"SalespersonCode-43", type text}, {"ShipmentDate-21", type datetime}, {"BilltoCounty-86", type text}, {"SelltoCounty-89", type text}, {"CustomerPriceGroup-34", type text}, {"ShiptoName-13", type text}, {"$Company", type text}, {"$DeliveredDateTime", type datetime}, {"BilltoCustomerNo-4", type text}, {"BilltoName-5", type text}, {"CustomerPostingGroup-31", type text}, {"DocumentDate-99", type datetime}, {"DueDate-24", type datetime}, {"GenBusPostingGroup-74", type text}, {"LocationCode-28", type text}, {"No-3", type text}, {"OrderDate-19", type datetime}, {"PostingDate-20", type datetime}, {"PostingDescription-22", type text}, {"SelltoCustomerName-79", type text}, {"SelltoCustomerNo-2", type text}, {"ShiptoCity-17", type text}, {"ShiptoCounty-92", type text}, {"SystemCreatedAt-2000000001", type datetime}, {"SystemCreatedBy-2000000002", type text}, {"SystemModifiedAt-2000000003", type datetime}, {"WTBABillHoldType-87570", type text}, {"WTPCPriceCalculated-89200", Int64.Type}, {"systemId-2000000000", type text}, {"timestamp-0", Int64.Type}, {"InsertDate", type datetime}, {"UpdateDate", type datetime}, {"ExternalDocumentNo-100", type text}})
in
  #"Changed column type";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "SalesInvoiceLine113_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared SalesInvoiceLine113 = let
  Source = Excel.Workbook(Web.Contents("https://www.dropbox.com/scl/fi/fl91oiquv6a71wrzfxsya/Req-3-Sample-data.xlsx?rlkey=74wh609g7pc5d79kccegid4th&st=xv3fjj3g&dl=1"), null, true),
  #"Navigation 1" = Source{[Item = "SalesInvoiceLine113", Kind = "Sheet"]}[Data],
  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ReturnReasonCode-6608", type text}, {"WTBAOrderChargeCode-87600", type text}, {"CustomerDiscGroup-7002", type text}, {"WTPCSalesPriceGroupCode-89200", type text}, {"WTBASampleReasonCode-87700", type text}, {"ShortcutDimension1Code-40", type text}, {"WTUSBeverageTaxAreaCode-88400", type text}, {"WTBABrandNo-87150", type text}, {"WTBAAlcoholTypeCode-87050", type text}, {"WTBABottleSize-87020", type text}, {"PostingGroup-8", type text}, {"UnitofMeasure-13", type text}, {"UnitofMeasureCode-5407", type text}, {"GenProdPostingGroup-75", type text}, {"WCTEWSalespersonCode-50000", type text}, {"CustomerPriceGroup-42", type text}, {"BilltoCustomerNo-68", type text}, {"GenBusPostingGroup-74", type text}, {"LocationCode-7", type text}, {"SelltoCustomerNo-2", type text}, {"OrderNo-65", type text}, {"Description-11", type text}, {"$Company", type text}, {"$DeliveredDateTime", type datetime}, {"AllowInvoiceDisc-32", Int64.Type}, {"AllowLineDisc-7001", Int64.Type}, {"Amount-29", type number}, {"AmountIncludingVAT-30", type number}, {"DocumentNo-3", type text}, {"LineDiscount-27", Int64.Type}, {"LineDiscountAmount-28", type number}, {"LineNo-4", Int64.Type}, {"QtyperUnitofMeasure-5404", type number}, {"Quantity-15", type number}, {"QuantityBase-5415", type number}, {"SystemCreatedAt-2000000001", type datetime}, {"SystemCreatedBy-2000000002", type text}, {"SystemModifiedAt-2000000003", type datetime}, {"Type-5", type text}, {"UnitCost-100", type number}, {"UnitCostLCY-23", type number}, {"UnitPrice-22", type number}, {"VAT-25", Int64.Type}, {"WCAR06SalesCommissionable-50100", Int64.Type}, {"WTBACasePack-87010", Int64.Type}, {"WTBAGallons-87301", type number}, {"WTBALiters-87300", type number}, {"WTBAQuantityBottle-87083", Int64.Type}, {"WTBAQuantityCase-87080", type number}, {"systemId-2000000000", type text}, {"timestamp-0", Int64.Type}, {"InsertDate", type datetime}, {"UpdateDate", type text}, {"No-6", type text}, {"ShipmentDate-10", type datetime}, {"WTBAOrderDate-87110", type datetime}, {"WTBADocumentDate-87100", type datetime}})
in
  #"Changed column type";
shared SalesCrMemoHeader114_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "2f1c0603-0152-47df-8538-a5b9c2fed106"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "6b9b268b-1bfc-4e19-9bea-11d7a6b8d89b"]}[Data],
  TableNavigation = Navigation_2{[Id = "SalesCrMemoHeader114", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
shared SalesCrMemoLine115_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "2f1c0603-0152-47df-8538-a5b9c2fed106"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "6b9b268b-1bfc-4e19-9bea-11d7a6b8d89b"]}[Data],
  TableNavigation = Navigation_2{[Id = "SalesCrMemoLine115", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
shared SalesInvoiceHeader112_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "2f1c0603-0152-47df-8538-a5b9c2fed106"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "6b9b268b-1bfc-4e19-9bea-11d7a6b8d89b"]}[Data],
  TableNavigation = Navigation_2{[Id = "SalesInvoiceHeader112", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
shared SalesInvoiceLine113_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "2f1c0603-0152-47df-8538-a5b9c2fed106"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "6b9b268b-1bfc-4e19-9bea-11d7a6b8d89b"]}[Data],
  TableNavigation = Navigation_2{[Id = "SalesInvoiceLine113", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
