[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "SalesHeader36_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared SalesHeader36 = let
  Source = Excel.Workbook(Web.Contents("https://www.dropbox.com/scl/fi/ap0ahhylkcnqrvkr8s4mv/SampleData-2.xlsx?rlkey=rwdw23siwiked9dmvkblaiopc&st=n927vq0j&dl=1"), null, true),
  #"Navigation 1" = Source{[Item = "SalesHeader36", Kind = "Sheet"]}[Data],
  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Promoted headers", {{"DocumentType-1", type text}, {"SelltoCustomerNo-2", type text}, {"No-3", type text}, {"BilltoCustomerNo-4", type text}, {"BilltoName-5", type text}, {"BilltoName2-6", type text}, {"BilltoAddress-7", type text}, {"BilltoAddress2-8", type text}, {"BilltoCity-9", type text}, {"BilltoContact-10", type text}, {"YourReference-11", type text}, {"ShiptoName-13", type text}, {"ShiptoName2-14", type text}, {"ShiptoAddress-15", type text}, {"ShiptoAddress2-16", type text}, {"ShiptoCity-17", type text}, {"ShiptoContact-18", type text}, {"OrderDate-19", Int64.Type}, {"PostingDate-20", Int64.Type}, {"ShipmentDate-21", Int64.Type}, {"PostingDescription-22", type text}, {"PaymentTermsCode-23", type text}, {"DueDate-24", Int64.Type}, {"PaymentDiscount-25", Int64.Type}, {"ShipmentMethodCode-27", type text}, {"LocationCode-28", type text}, {"ShortcutDimension1Code-29", type text}, {"ShortcutDimension2Code-30", type text}, {"CustomerPostingGroup-31", type text}, {"CurrencyCode-32", type text}, {"CurrencyFactor-33", Int64.Type}, {"CustomerPriceGroup-34", type text}, {"PricesIncludingVAT-35", Int64.Type}, {"InvoiceDiscCode-37", type text}, {"CustomerDiscGroup-40", type text}, {"LanguageCode-41", type text}, {"FormatRegion-42", type text}, {"SalespersonCode-43", type text}, {"OrderClass-45", type text}, {"NoPrinted-47", Int64.Type}, {"OnHold-51", type text}, {"AppliestoDocType-52", type text}, {"AppliestoDocNo-53", type text}, {"BalAccountNo-55", type text}, {"Ship-57", Int64.Type}, {"Invoice-58", Int64.Type}, {"PrintPostedDocuments-59", Int64.Type}, {"ShippingNo-62", type text}, {"PostingNo-63", type text}, {"LastShippingNo-64", type text}, {"LastPostingNo-65", type text}, {"PrepaymentNo-66", type text}, {"LastPrepaymentNo-67", type text}, {"PrepmtCrMemoNo-68", type text}, {"LastPrepmtCrMemoNo-69", type text}, {"VATRegistrationNo-70", type text}, {"CombineShipments-71", Int64.Type}, {"RegistrationNumber-72", type text}, {"ReasonCode-73", type text}, {"GenBusPostingGroup-74", type text}, {"EU3PartyTrade-75", Int64.Type}, {"TransactionType-76", type text}, {"TransportMethod-77", type text}, {"VATCountryRegionCode-78", type text}, {"SelltoCustomerName-79", type text}, {"SelltoCustomerName2-80", type text}, {"SelltoAddress-81", type text}, {"SelltoAddress2-82", type text}, {"SelltoCity-83", type text}, {"SelltoContact-84", type text}, {"BilltoCounty-86", type text}, {"BilltoCountryRegionCode-87", type text}, {"SelltoCounty-89", type text}, {"SelltoCountryRegionCode-90", type text}, {"ShiptoCounty-92", type text}, {"ShiptoCountryRegionCode-93", type text}, {"BalAccountType-94", type text}, {"ExitPoint-97", type text}, {"Correction-98", Int64.Type}, {"DocumentDate-99", Int64.Type}, {"Area-101", type text}, {"TransactionSpecification-102", type text}, {"PaymentMethodCode-104", type text}, {"ShippingAgentCode-105", type text}, {"PackageTrackingNo-106", type text}, {"NoSeries-107", type text}, {"PostingNoSeries-108", type text}, {"ShippingNoSeries-109", type text}, {"TaxAreaCode-114", type text}, {"TaxLiable-115", Int64.Type}, {"VATBusPostingGroup-116", type text}, {"Reserve-117", type text}, {"AppliestoID-118", type text}, {"VATBaseDiscount-119", Int64.Type}, {"Status-120", type text}, {"InvoiceDiscountCalculation-121", type text}, {"InvoiceDiscountValue-122", Int64.Type}, {"SendICDocument-123", Int64.Type}, {"ICStatus-124", type text}, {"SelltoICPartnerCode-125", type text}, {"BilltoICPartnerCode-126", type text}, {"ICReferenceDocumentNo-127", type text}, {"ICDirection-129", type text}, {"Prepayment-130", Int64.Type}, {"PrepaymentNoSeries-131", type text}, {"CompressPrepayment-132", Int64.Type}, {"PrepaymentDueDate-133", Int64.Type}, {"PrepmtCrMemoNoSeries-134", type text}, {"PrepmtPostingDescription-135", type text}, {"PrepmtPaymentTermsCode-139", type text}, {"PrepmtPaymentDiscount-140", Int64.Type}, {"QuoteNo-151", type text}, {"QuoteValidUntilDate-152", type text}, {"QuoteSenttoCustomer-153", type text}, {"QuoteAccepted-154", Int64.Type}, {"QuoteAcceptedDate-155", type text}, {"JobQueueStatus-160", type text}, {"JobQueueEntryID-161", type text}, {"CompanyBankAccountCode-163", type text}, {"IncomingDocumentEntryNo-165", Int64.Type}, {"AltVATRegistrationNo-166", Int64.Type}, {"AltGenBusPostingGroup-167", Int64.Type}, {"AltVATBusPostingGroup-168", Int64.Type}, {"IsTest-170", Int64.Type}, {"SelltoPhoneNo-171", type text}, {"SelltoEMail-172", type text}, {"JournalTemplName-178", type text}, {"VATReportingDate-179", Int64.Type}, {"RcvdfromCountRegionCode-181", type text}, {"ShiptoPhoneNo-210", type text}, {"DimensionSetID-480", Int64.Type}, {"PaymentServiceSetID-600", Int64.Type}, {"DirectDebitMandateID-1200", type text}, {"DocNoOccurrence-5048", Int64.Type}, {"CampaignNo-5050", type text}, {"SelltoContactNo-5052", type text}, {"BilltoContactNo-5053", type text}, {"OpportunityNo-5055", type text}, {"SelltoCustomerTemplCode-5056", type text}, {"BilltoCustomerTemplCode-5057", type text}, {"ResponsibilityCenter-5700", type text}, {"ShippingAdvice-5750", type text}, {"PostingfromWhseRef-5753", Int64.Type}, {"PromisedDeliveryDate-5791", type text}, {"ShippingTime-5792", type text}, {"OutboundWhseHandlingTime-5793", type text}, {"ShippingAgentServiceCode-5794", type text}, {"Receive-5800", Int64.Type}, {"ReturnReceiptNo-5801", type text}, {"ReturnReceiptNoSeries-5802", type text}, {"LastReturnReceiptNo-5803", type text}, {"PriceCalculationMethod-7000", type text}, {"AllowLineDisc-7001", Int64.Type}, {"GetShipmentUsed-7200", Int64.Type}, {"RecurringBilling-8051", Int64.Type}, {"SubContractDetailOverview-8052", type text}, {"AssignedUserID-9000", type text}, {"SalesTaxAmountRounding-10000", Int64.Type}, {"PrepmtSalesTaxRoundingAmt-10001", Int64.Type}, {"ShiptoUPSZone-10005", type text}, {"TaxExemptionNo-10015", type text}, {"STETransactionID-10018", type text}, {"TransitfromDateTime-10045", type text}, {"TransitHours-10046", Int64.Type}, {"TransitDistance-10047", Int64.Type}, {"InsurerName-10048", type text}, {"InsurerPolicyNumber-10049", type text}, {"ForeignTrade-10050", Int64.Type}, {"VehicleCode-10051", type text}, {"Trailer1-10052", type text}, {"Trailer2-10053", type text}, {"MedicalInsurerName-10056", type text}, {"MedicalInsPolicyNumber-10057", type text}, {"SATWeightUnitOfMeasure-10058", type text}, {"SATInternationalTradeTerm-10059", type text}, {"ExchangeRateUSD-10060", Int64.Type}, {"SATCustomsRegime-10061", type text}, {"SATTransferReason-10062", type text}, {"PrepmtIncludeTax-12600", Int64.Type}, {"CFDIPurpose-27000", type text}, {"CFDIRelation-27001", type text}, {"CFDIExportCode-27004", type text}, {"CFDIPeriod-27005", type text}, {"SATAddressID-27009", Int64.Type}, {"ShpfyOrderId-30100", Int64.Type}, {"ShpfyOrderNo-30101", type text}, {"ShpfyRefundId-30103", Int64.Type}, {"WCSAL34SampleReasonCode-50050", type text}, {"WCAR06SalesCommissionable-50100", Int64.Type}, {"WCINT00ExcludefromExport-50200", Int64.Type}, {"WCINT00ExportAgain-50201", Int64.Type}, {"WCINT00Exported-50202", Int64.Type}, {"WCINT00ExportError-50204", Int64.Type}, {"WCINT00ExportErrorMessage-50205", type text}, {"WCINT00ExportFileName-50206", type text}, {"WCINT04PAOrderNo-50650", type text}, {"WCINT04PASalesRep-50651", type text}, {"WCINT04CreatedBy-50652", type text}, {"WTBASOReleasePriority-87000", type text}, {"WTBASalesRegionCode-87003", type text}, {"WTBACategoryCode-87004", type text}, {"WTBAOrderTypeCode-87007", type text}, {"WTBASampleOrder-87008", Int64.Type}, {"WTBACreditClassCode-87109", type text}, {"WTBACalledFromWhseRelease-87150", Int64.Type}, {"WTBACalledFromWhseReopen-87151", Int64.Type}, {"WTBAPriceCategoryCode-87250", type text}, {"WTBALastEmailSentDateTime-87350", type text}, {"WTBASiteCode-87400", type text}, {"WTBASiteOrderID-87401", Int64.Type}, {"WTBAPickupCode-87550", type text}, {"WTBAPickupName-87551", type text}, {"WTBAPickupName2-87552", type text}, {"WTBAPickupAddress-87553", type text}, {"WTBAPickupAddress2-87554", type text}, {"WTBAPickupCity-87555", type text}, {"WTBAPickupCounty-87556", type text}, {"WTBAPickupPostCode-87557", type text}, {"WTBAPickupCountryRegCode-87558", type text}, {"WTBAPickupContact-87559", type text}, {"WTBAPickupPhoneNo-87560", type text}, {"WTBAPickupFaxNo-87561", type text}, {"WTBAPickupEmail-87562", type text}, {"WTBABillHoldType-87570", type text}, {"WTBAOrderChargesHandled-87600", Int64.Type}, {"WTBACoopCode-87650", type text}, {"WTBASOReviewStatus-87851", type text}, {"WTBAPostingError-87860", Int64.Type}, {"WTUSBeverageTaxAreaCode-88400", type text}, {"WTPCPriceCalculated-89200", Int64.Type}, {"WTPCFamilyPlanQuantity-89202", Int64.Type}, {"WTPCSalesPriceLinkId-89204", Int64.Type}, {"WMDMPOS-23044500", Int64.Type}, {"ERCPromisedShipmentDate-71276886", type text}, {"ERCAPMJobNumber-71276890", type text}, {"ERCFOBOptionCode-71276891", type text}, {"ERCSQExpireEmailSent-71276892", type text}, {"ERCSQExpiredEmailSent-71276893", type text}, {"ERCExemptfromPrePayApp-71276894", Int64.Type}, {"ERCChargeShipRushFreight-71276895", Int64.Type}, {"ERCShipRushCollectAcctNo-71276896", type text}, {"ERCShipRushPaymentType-71276897", type text}, {"ERCPrintOptionCode-71276898", type text}, {"ERCBlindShippingOption-71276899", type text}, {"ERCBlindName-71276901", type text}, {"ERCBlindAddress-71276902", type text}, {"ERCBlindAddress2-71276903", type text}, {"ERCBlindCity-71276904", type text}, {"ERCBlindState-71276905", type text}, {"ERCBlindPostCode-71276906", type text}, {"ERCBlindCountryCode-71276907", type text}, {"ERCRecurringPostingOption-71276908", type text}, {"ERCRecurringFrequency-71276909", type text}, {"ERCNextOccuranceDate-71276910", type text}, {"ERCRecurringExpirationDate-71276911", type text}, {"ERCProjectNo-71276912", type text}, {"ERCPhaseNo-71276913", type text}, {"ERCTaskNo-71276914", type text}, {"ERCPurchaseCodeOption-71276915", type text}, {"ERCNextOccurancePostDate-71276916", type text}, {"ERCSpecialOrderOption-71276917", type text}, {"ERCPrePayAmounttoApply-71276918", Int64.Type}, {"ERCRecurringInvoice-71276919", Int64.Type}, {"ERCRecurringOnHold-71276920", Int64.Type}, {"ERCRecurringOnHoldUntil-71276921", type text}, {"ERCAREmail-71276924", type text}, {"ERCSRShiptoEmail-71276925", type text}, {"ERCRecurringDocumentNo-71276926", type text}, {"ERCRecurringExpired-71276927", Int64.Type}, {"ERCLinkedWorkOrder-71276928", type text}, {"timestamp-0", Int64.Type}, {"systemId-2000000000", type text}, {"SystemCreatedAt-2000000001", type datetime}, {"SystemCreatedBy-2000000002", type text}, {"SystemModifiedAt-2000000003", type datetime}, {"SystemModifiedBy-2000000004", type text}, {"$Company", type text}, {"$DeliveredDateTime", type datetime}, {"ShiptoCode-12", type text}, {"PmtDiscountDate-26", type date}, {"BilltoPostCode-85", type text}, {"SelltoPostCode-88", type text}, {"ShiptoPostCode-91", type text}, {"ExternalDocumentNo-100", type text}, {"PrepmtPmtDiscountDate-138", type date}, {"RequestedDeliveryDate-5790", type date}, {"WCINT00DateTimeExported-50203", type datetime}, {"WTPCPriceCalculatedDate-89201", type datetime}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Changed column type 2", {{"DocumentDate-99", type date}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Changed column type", {{"DueDate-24", type date}}),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Changed column type 1", {{"OrderDate-19", type date}}),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Changed column type 3", {{"PostingDate-20", type date}}),
  #"Changed column type 5" = Table.TransformColumnTypes(#"Changed column type 4", {{"PrepaymentDueDate-133", type date}}),
  #"Changed column type 6" = Table.TransformColumnTypes(#"Changed column type 5", {{"ShipmentDate-21", type date}}),
  #"Changed column type 7" = Table.TransformColumnTypes(#"Changed column type 6", {{"VATReportingDate-179", type date}})
in
  #"Changed column type 7";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "SalesLine37_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared SalesLine37 = let
  Source = Excel.Workbook(Web.Contents("https://www.dropbox.com/scl/fi/ap0ahhylkcnqrvkr8s4mv/SampleData-2.xlsx?rlkey=rwdw23siwiked9dmvkblaiopc&st=n927vq0j&dl=1"), null, true),
  #"Navigation 1" = Source{[Item = "SalesLine37", Kind = "Sheet"]}[Data],
  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"$Company", type text}, {"$DeliveredDateTime", type datetime}, {"timestamp-0", Int64.Type}, {"systemId-2000000000", type text}, {"SystemCreatedAt-2000000001", type datetime}, {"SystemCreatedBy-2000000002", type text}, {"SystemModifiedAt-2000000003", type datetime}, {"SystemModifiedBy-2000000004", type text}, {"ERCSelectedPurchQuoteNo-71276918", type text}, {"ERCSelectedPQLineNo-71276919", Int64.Type}, {"ERCRMAAutoDispose-71276920", Int64.Type}, {"ERCAPMDisplayUnitPrice-71276921", Int64.Type}, {"ERCAPMDisplayAmount-71276922", Int64.Type}, {"ERCRecurCommExpireDate-71276928", type text}, {"WTPCSalesPriceCalcMethod-89201", type text}, {"WTPCSalesPriceCalcQty-89202", type number}, {"WTPCSalesPriceCategoryCode-89203", type text}, {"WTPCSalesPriceLinkId-89204", Int64.Type}, {"WTIAAllocationInheritCode-90110", type text}, {"ERCGenSelectionOption-71276915", type text}, {"WTCBDeplAllowUnitAmtType-89000", type text}, {"WTCBDeplAllowUnitAmt-89010", Int64.Type}, {"WTCBDeplAllowLineUnitAmt-89020", Int64.Type}, {"WTCBDeplAllowLineAmt-89030", Int64.Type}, {"WTCBBillBack-89050", Int64.Type}, {"WTPCSalesPriceGroupCode-89200", type text}, {"WTBANetWeight-87870", Int64.Type}, {"WTBAQuantityPallet-87880", type number}, {"WTUSBeverageTaxAreaCode-88400", type text}, {"WTUSBeverageTax-88401", Int64.Type}, {"WTUSExciseTaxCode-88650", type text}, {"WTUSExciseTaxClass-88651", type text}, {"WTBASampleTotalAmount-87701", Int64.Type}, {"WTBABudgetSalespersonCode-87702", type text}, {"WTBAStatus-87703", type text}, {"WTBAGrossWeight-87823", Int64.Type}, {"WTBAVolume-87824", type number}, {"WTBASOReviewStatus-87851", type text}, {"WTBAOriginalQtyCase-87342", Int64.Type}, {"WTBAOriginalQtyBottle-87343", Int64.Type}, {"WTBABillHoldEntryNo-87570", Int64.Type}, {"WTBAOrderChargeCode-87600", type text}, {"WTBACoopCode-87650", type text}, {"WTBASampleReasonCode-87700", type text}, {"WTBABrandNo-87150", type text}, {"WTBAPriceCategoryCode-87250", type text}, {"WTBALiters-87300", type number}, {"WTBAGallons-87301", type number}, {"WTBAOriginalQuantity-87340", Int64.Type}, {"WTBAOriginalQuantityBase-87341", Int64.Type}, {"WTBARetQtyReceivedBottle-87092", Int64.Type}, {"WTBARetQtyReceivedCase-87093", Int64.Type}, {"WTBAOutstandingQtyCase-87094", type number}, {"WTBAOutstandingQtyBottle-87095", Int64.Type}, {"WTBADocumentDate-87100", Int64.Type}, {"WTBAOrderDate-87110", Int64.Type}, {"WTBAQtytoInvoiceCase-87086", type number}, {"WTBAQtytoInvoiceBottle-87087", Int64.Type}, {"WTBAQtyInvoicedCase-87088", Int64.Type}, {"WTBAQtyInvoicedBottle-87089", Int64.Type}, {"WTBARetQtytoRecvBottle-87090", Int64.Type}, {"WTBARetQtytoRecvCase-87091", Int64.Type}, {"WTBAQuantityCase-87080", type number}, {"WTBAQtytoShipCase-87081", type number}, {"WTBAQtyShippedCase-87082", Int64.Type}, {"WTBAQuantityBottle-87083", Int64.Type}, {"WTBAQtytoShipBottle-87084", Int64.Type}, {"WTBAQtyShippedBottle-87085", Int64.Type}, {"WTBABottleSize-87020", type text}, {"WTBASalesPriceOverride-87030", Int64.Type}, {"WTBALineDiscountUnitAmount-87040", Int64.Type}, {"WTBALineDiscAmountCase-87041", Int64.Type}, {"WTBALineDiscAmountBottle-87042", Int64.Type}, {"WTBAAlcoholTypeCode-87050", type text}, {"WCMBCLastOrderQuantity-50400", Int64.Type}, {"WCMBCLastOrderUOMCode-50401", type text}, {"WCMBCLastOrderUnitPrice-50402", Int64.Type}, {"WCMBCLastOrderShipmentDate-50403", type text}, {"WTBALinkedLineNo-87000", Int64.Type}, {"WTBACasePack-87010", Int64.Type}, {"WCAR06DefaultComm-50114", Int64.Type}, {"WCAR06DefaultCommAmount-50115", type number}, {"WCSAL04PalletDiscGroupCode-50121", type text}, {"WCINT01ShortShipped-50220", Int64.Type}, {"WCINT01ShortShipOrigQty-50221", Int64.Type}, {"ShpfyRefundShippingLineId-30105", Int64.Type}, {"WCTEWSalespersonCode-50000", type text}, {"WCAR06SalesCommissionable-50100", Int64.Type}, {"WCAR06ManualComm-50111", Int64.Type}, {"WCAR06ManualCommAmount-50112", Int64.Type}, {"WCAR06MaxComm-50113", Int64.Type}, {"CustomTransitNumber-10003", type text}, {"SATCustomsDocumentType-10004", type text}, {"ShpfyOrderLineId-30100", Int64.Type}, {"ShpfyOrderNo-30101", type text}, {"ShpfyRefundId-30103", Int64.Type}, {"ShpfyRefundLineId-30104", Int64.Type}, {"RecurringBillingto-8054", type text}, {"Discount-8058", Int64.Type}, {"ExcludefromDocTotal-8059", Int64.Type}, {"PackageTrackingNo-10000", type text}, {"RetentionAttachedtoLineNo-10001", Int64.Type}, {"RetentionVAT-10002", Int64.Type}, {"PriceCalculationMethod-7000", type text}, {"AllowLineDisc-7001", Int64.Type}, {"CustomerDiscGroup-7002", type text}, {"Subtype-7003", type text}, {"Pricedescription-7004", type text}, {"RecurringBillingfrom-8053", type text}, {"TotalCO2e-6215", Int64.Type}, {"PostedTotalCO2e-6216", Int64.Type}, {"ReturnReceiptNo-6600", type text}, {"ReturnReceiptLineNo-6601", Int64.Type}, {"ReturnReasonCode-6608", type text}, {"CopiedFromPostedDoc-6610", Int64.Type}, {"BOMItemNo-5909", type text}, {"SustAccountNo-6210", type text}, {"SustAccountName-6211", type text}, {"SustAccountCategory-6212", type text}, {"SustAccountSubcategory-6213", type text}, {"CO2eperUnit-6214", Int64.Type}, {"RetQtyRcdNotInvdBase-5806", Int64.Type}, {"ReturnRcdNotInvd-5807", Int64.Type}, {"ReturnRcdNotInvdLCY-5808", Int64.Type}, {"ReturnQtyReceived-5809", Int64.Type}, {"ReturnQtyReceivedBase-5810", Int64.Type}, {"ApplfromItemEntry-5811", Int64.Type}, {"ShippingAgentCode-5796", type text}, {"ShippingAgentServiceCode-5797", type text}, {"AllowItemChargeAssignment-5800", Int64.Type}, {"ReturnQtytoReceive-5803", Int64.Type}, {"ReturnQtytoReceiveBase-5804", Int64.Type}, {"ReturnQtyRcdNotInvd-5805", Int64.Type}, {"PromisedDeliveryDate-5791", type text}, {"ShippingTime-5792", type text}, {"OutboundWhseHandlingTime-5793", type text}, {"PlannedDeliveryDate-5794", Int64.Type}, {"PlannedShipmentDate-5795", Int64.Type}, {"SpecialOrderPurchLineNo-5715", Int64.Type}, {"ItemReferenceNo-5725", type text}, {"ItemReferenceUnitofMeasure-5726", type text}, {"ItemReferenceType-5727", type text}, {"ItemReferenceTypeNo-5728", type text}, {"CompletelyShipped-5752", Int64.Type}, {"OriginallyOrderedVarCode-5704", type text}, {"ItemCategoryCode-5709", type text}, {"Nonstock-5710", Int64.Type}, {"PurchasingCode-5711", type text}, {"SpecialOrder-5713", Int64.Type}, {"SpecialOrderPurchaseNo-5714", type text}, {"DepruntilFAPostingDate-5605", Int64.Type}, {"DuplicateinDepreciationBook-5612", type text}, {"UseDuplicationList-5613", Int64.Type}, {"ResponsibilityCenter-5700", type text}, {"OutofStockSubstitution-5701", Int64.Type}, {"OriginallyOrderedNo-5703", type text}, {"QtytoShipBase-5418", type number}, {"QtyShippedNotInvdBase-5458", Int64.Type}, {"QtyShippedBase-5460", Int64.Type}, {"QtyInvoicedBase-5461", Int64.Type}, {"FAPostingDate-5600", type text}, {"DepreciationBookCode-5602", type text}, {"QtyRoundingPrecision-5406", type number}, {"UnitofMeasureCode-5407", type text}, {"QtyRoundingPrecisionBase-5408", type number}, {"QuantityBase-5415", type number}, {"OutstandingQtyBase-5416", type number}, {"QtytoInvoiceBase-5417", type number}, {"SelectedAllocAccountNo-2675", type text}, {"AllocationAccountNo-2678", type text}, {"VariantCode-5402", type text}, {"BinCode-5403", type text}, {"QtyperUnitofMeasure-5404", type number}, {"Planned-5405", Int64.Type}, {"QtytoAssembletoOrder-900", Int64.Type}, {"QtytoAsmtoOrderBase-901", Int64.Type}, {"JobTaskNo-1001", type text}, {"JobContractEntryNo-1002", Int64.Type}, {"DeferralCode-1700", type text}, {"ReturnsDeferralStartDate-1702", type text}, {"PrepmtVATDiffDeducted-137", Int64.Type}, {"ICItemReferenceNo-138", type text}, {"PmtDiscountAmount-145", Int64.Type}, {"PrepmtPmtDiscountAmount-146", Int64.Type}, {"LineDiscountCalculation-180", type text}, {"DimensionSetID-480", Int64.Type}, {"PrepmtAmountInvInclVAT-124", Int64.Type}, {"PrepmtAmountInvLCY-129", Int64.Type}, {"ICPartnerCode-130", type text}, {"PrepmtVATAmountInvLCY-132", Int64.Type}, {"PrepaymentVATDifference-135", Int64.Type}, {"PrepmtVATDifftoDeduct-136", Int64.Type}, {"PrepaymentTaxAreaCode-118", type text}, {"PrepaymentTaxLiable-119", Int64.Type}, {"PrepaymentTaxGroupCode-120", type text}, {"PrepmtAmttoDeduct-121", Int64.Type}, {"PrepmtAmtDeducted-122", Int64.Type}, {"PrepaymentLine-123", Int64.Type}, {"PrepmtAmtInclVAT-112", Int64.Type}, {"PrepaymentAmount-113", Int64.Type}, {"PrepmtVATBaseAmt-114", Int64.Type}, {"PrepaymentVAT-115", Int64.Type}, {"PrepmtVATCalcType-116", type text}, {"PrepaymentVATIdentifier-117", type text}, {"VATIdentifier-106", type text}, {"ICPartnerRefType-107", type text}, {"ICPartnerReference-108", type text}, {"Prepayment-109", Int64.Type}, {"PrepmtLineAmount-110", Int64.Type}, {"PrepmtAmtInv-111", Int64.Type}, {"VATBaseAmount-99", type number}, {"UnitCost-100", type number}, {"SystemCreatedEntry-101", Int64.Type}, {"LineAmount-103", type number}, {"VATDifference-104", Int64.Type}, {"InvDiscAmounttoInvoice-105", Int64.Type}, {"OutstandingAmountLCY-92", type number}, {"ShippedNotInvoicedLCY-93", Int64.Type}, {"ShippedNotInvLCYNoVAT-94", Int64.Type}, {"Reserve-96", type text}, {"BlanketOrderNo-97", type text}, {"BlanketOrderLineNo-98", Int64.Type}, {"TaxLiable-86", Int64.Type}, {"TaxGroupCode-87", type text}, {"VATClauseCode-88", type text}, {"VATBusPostingGroup-89", type text}, {"VATProdPostingGroup-90", type text}, {"CurrencyCode-91", type text}, {"AttachedtoLineNo-80", Int64.Type}, {"ExitPoint-81", type text}, {"Area-82", type text}, {"TransactionSpecification-83", type text}, {"TaxCategory-84", type text}, {"TaxAreaCode-85", type text}, {"DropShipment-73", Int64.Type}, {"GenBusPostingGroup-74", type text}, {"GenProdPostingGroup-75", type text}, {"VATCalculationType-77", type text}, {"TransactionType-78", type text}, {"TransportMethod-79", type text}, {"ShipmentLineNo-64", Int64.Type}, {"Profit-67", Int64.Type}, {"BilltoCustomerNo-68", type text}, {"InvDiscountAmount-69", Int64.Type}, {"PurchaseOrderNo-71", type text}, {"PurchOrderLineNo-72", Int64.Type}, {"OutstandingAmount-57", type number}, {"QtyShippedNotInvoiced-58", Int64.Type}, {"ShippedNotInvoiced-59", Int64.Type}, {"QuantityShipped-60", Int64.Type}, {"QuantityInvoiced-61", Int64.Type}, {"ShipmentNo-63", type text}, {"ShortcutDimension1Code-40", type text}, {"ShortcutDimension2Code-41", type text}, {"CustomerPriceGroup-42", type text}, {"JobNo-45", type text}, {"WorkTypeCode-52", type text}, {"RecalculateInvoiceDisc-56", Int64.Type}, {"AllowInvoiceDisc-32", Int64.Type}, {"GrossWeight-34", Int64.Type}, {"NetWeight-35", Int64.Type}, {"UnitsperParcel-36", Int64.Type}, {"UnitVolume-37", type number}, {"AppltoItemEntry-38", Int64.Type}, {"UnitCostLCY-23", type number}, {"VAT-25", Int64.Type}, {"LineDiscount-27", Int64.Type}, {"LineDiscountAmount-28", Int64.Type}, {"Amount-29", type number}, {"AmountIncludingVAT-30", type number}, {"UnitofMeasure-13", type text}, {"Quantity-15", type number}, {"OutstandingQuantity-16", type number}, {"QtytoInvoice-17", type number}, {"QtytoShip-18", type number}, {"UnitPrice-22", type number}, {"No-6", type text}, {"LocationCode-7", type text}, {"PostingGroup-8", type text}, {"ShipmentDate-10", Int64.Type}, {"Description-11", type text}, {"Description2-12", type text}, {"DocumentType-1", type text}, {"SelltoCustomerNo-2", type text}, {"DocumentNo-3", type text}, {"LineNo-4", Int64.Type}, {"Type-5", type text}, {"RequestedDeliveryDate-5790", type date}, {"WCSAL04SampleDiscGroupCode-50120", type text}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Changed column type", {{"ShipmentDate-10", type date}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Changed column type 1", {{"PlannedDeliveryDate-5794", type date}}),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Changed column type 2", {{"PlannedShipmentDate-5795", type date}}),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Changed column type 3", {{"WTBADocumentDate-87100", type date}})
in
  #"Changed column type 4";
shared SalesHeader36_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "2f1c0603-0152-47df-8538-a5b9c2fed106"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "6b9b268b-1bfc-4e19-9bea-11d7a6b8d89b"]}[Data],
  TableNavigation = Navigation_2{[Id = "SalesHeader36", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
shared SalesLine37_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "2f1c0603-0152-47df-8538-a5b9c2fed106"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "6b9b268b-1bfc-4e19-9bea-11d7a6b8d89b"]}[Data],
  TableNavigation = Navigation_2{[Id = "SalesLine37", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
