[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Customer18_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared Customer18 = let
  Source = Excel.Workbook(Web.Contents("https://www.dropbox.com/scl/fi/4ce8rhjof5kjjoo1vndb1/Customer-and-Item.xlsx?rlkey=8n3qg2hntlii9r0yyp3avoe38&st=qiwunntm&dl=1"), null, true),
  #"Navigation 1" = Source{[Item = "Customer18", Kind = "Sheet"]}[Data],
  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"No-1", type text}, {"Name-2", type text}, {"SearchName-3", type text}, {"Name2-4", type text}, {"Address-5", type text}, {"Address2-6", type text}, {"City-7", type text}, {"Contact-8", type text}, {"TelexNo-10", type text}, {"DocumentSendingProfile-11", type text}, {"ShiptoCode-12", type text}, {"OurAccountNo-14", type text}, {"TerritoryCode-15", type text}, {"GlobalDimension1Code-16", type text}, {"GlobalDimension2Code-17", type text}, {"ChainName-18", type text}, {"BudgetedAmount-19", Int64.Type}, {"CreditLimitLCY-20", Int64.Type}, {"CustomerPostingGroup-21", type text}, {"CurrencyCode-22", type text}, {"CustomerPriceGroup-23", type text}, {"LanguageCode-24", type text}, {"RegistrationNumber-25", type text}, {"StatisticsGroup-26", Int64.Type}, {"PaymentTermsCode-27", type text}, {"FinChargeTermsCode-28", type text}, {"SalespersonCode-29", type text}, {"ShipmentMethodCode-30", type text}, {"ShippingAgentCode-31", type text}, {"PlaceofExport-32", type text}, {"InvoiceDiscCode-33", type text}, {"CustomerDiscGroup-34", type text}, {"CountryRegionCode-35", type text}, {"CollectionMethod-36", type text}, {"Amount-37", Int64.Type}, {"Blocked-39", type text}, {"InvoiceCopies-40", Int64.Type}, {"LastStatementNo-41", Int64.Type}, {"PrintStatements-42", Int64.Type}, {"BilltoCustomerNo-45", type text}, {"Priority-46", Int64.Type}, {"PaymentMethodCode-47", type text}, {"FormatRegion-48", type text}, {"LastModifiedDateTime-53", type datetime}, {"LastDateModified-54", type date}, {"ApplicationMethod-80", type text}, {"PricesIncludingVAT-82", Int64.Type}, {"LocationCode-83", type text}, {"FaxNo-84", type text}, {"TelexAnswerBack-85", type text}, {"CombineShipments-87", Int64.Type}, {"GenBusPostingGroup-88", type text}, {"GLN-90", type text}, {"PostCode-91", Int64.Type}, {"County-92", type text}, {"EORINumber-93", type text}, {"UseGLNinElectronicDocument-95", Int64.Type}, {"EMail-102", type text}, {"HomePage-103", type text}, {"ReminderTermsCode-104", type text}, {"NoSeries-107", type text}, {"TaxAreaCode-108", type text}, {"TaxLiable-109", Int64.Type}, {"VATBusPostingGroup-110", type text}, {"Reserve-115", type text}, {"BlockPaymentTolerance-116", Int64.Type}, {"ICPartnerCode-119", type text}, {"Prepayment-124", Int64.Type}, {"PartnerType-132", type text}, {"IntrastatPartnerType-133", type text}, {"ExcludefromPmtPractices-134", Int64.Type}, {"PrivacyBlocked-150", Int64.Type}, {"DisableSearchbyName-160", Int64.Type}, {"AllowMultiplePostingGroups-175", Int64.Type}, {"PreferredBankAccountCode-288", type text}, {"CashFlowPaymentTermsCode-840", type text}, {"PrimaryContactNo-5049", type text}, {"ContactType-5050", type text}, {"ResponsibilityCenter-5700", type text}, {"ShippingAdvice-5750", type text}, {"ShippingTime-5790", type text}, {"ShippingAgentServiceCode-5792", type text}, {"ServiceZoneCode-5900", type text}, {"CombineServiceShipments-5930", Int64.Type}, {"PriceCalculationMethod-7000", type text}, {"AllowLineDisc-7001", Int64.Type}, {"BaseCalendarCode-7600", type text}, {"CopySelltoAddrtoQteFrom-7601", type text}, {"ValidateEUVatRegNo-7602", Int64.Type}, {"CurrencyId-8001", type text}, {"PaymentTermsId-8002", type text}, {"ShipmentMethodId-8003", type text}, {"PaymentMethodId-8004", type text}, {"TaxAreaID-9003", type text}, {"ContactID-9005", type text}, {"ContactGraphId-9006", type text}, {"UPSZone-10004", type text}, {"TaxExemptionNo-10015", type text}, {"BankCommunication-10017", type text}, {"CheckDateFormat-10018", type text}, {"CheckDateSeparator-10019", type text}, {"RFCNo-10023", type text}, {"CURPNo-10024", type text}, {"StateInscription-10025", type text}, {"TaxIdentificationType-14020", type text}, {"CFDIPurpose-27000", type text}, {"CFDIRelation-27001", type text}, {"SATTaxRegimeClassification-27002", type text}, {"CFDIExportCode-27004", type text}, {"CFDIGeneralPublic-27005", Int64.Type}, {"CFDIPeriod-27006", type text}, {"CFDICustomerName-27007", type text}, {"WCTEWPrestige-50000", Int64.Type}, {"WCSAL17PersonalGuarantee-50050", Int64.Type}, {"WCAR06SalesCommission-50100", Int64.Type}, {"WCSAL04SampleDiscGroupCode-50120", type text}, {"WCSAL04PalletDiscGroupCode-50121", type text}, {"WCINT01ExcludefromExport-50220", Int64.Type}, {"WTBACorporateName-87000", type text}, {"WTBAOrderTypeCode-87007", type text}, {"WTBACategoryCode-87020", type text}, {"WTBAOnPremise-87030", Int64.Type}, {"WTBABondNo-87060", type text}, {"WTBACreditClassCode-87109", type text}, {"WTBAHistCreditClassCode-87110", type text}, {"WTBAHistPmtTermsCode-87120", type text}, {"WTBASalesRegionCode-87152", type text}, {"WTBAPriceCategoryCode-87250", type text}, {"WTBAPickupAddressCode-87550", type text}, {"WTBABillHoldBinCode-87570", type text}, {"WTBASalespersonLocCode-87720", type text}, {"WTBASalespersonBinCode-87721", type text}, {"WTUSBeverageTaxAreaCode-88400", type text}, {"WTUSExportCustomer-88650", Int64.Type}, {"WTIAAllocate-90100", Int64.Type}, {"WTIAAllocationCode-90101", type text}, {"WTIAAllocationInheritCode-90102", type text}, {"ERCAveragePayDays-71276875", Int64.Type}, {"ERCStatementDeliveryOption-71276876", type text}, {"ERCLastStatementDateTime-71276877", type text}, {"ERCLastStatementBy-71276878", type text}, {"ERCAREmail-71276879", type text}, {"ERCInvoiceConsolidateOption-71276880", type text}, {"ERCInvoiceDeliveryDOW-71276881", type text}, {"ERCDoNotSendReminders-71276882", Int64.Type}, {"ERCEmailInvoiceonPosting-71276883", Int64.Type}, {"ERCEmailCMonPosting-71276884", Int64.Type}, {"ERCEmailPRonPosting-71276885", Int64.Type}, {"ERCInvoiceEmailSubject-71276886", type text}, {"ERCChargeSRFreight-71276888", Int64.Type}, {"ERCSRFreeFreightThreshold-71276889", Int64.Type}, {"ERCSRCollectAccountNo-71276890", type text}, {"ERCSRPaymentType-71276891", type text}, {"ERCBlindShippingOption-71276899", type text}, {"ERCBlindName-71276901", type text}, {"ERCBlindAddress-71276902", type text}, {"ERCBlindAddress2-71276903", type text}, {"ERCBlindCity-71276904", type text}, {"ERCBlindState-71276905", type text}, {"ERCBlindPostCode-71276906", type text}, {"ERCBlindCountryCode-71276907", type text}, {"ERCDISRouteNo-71276908", type text}, {"ERCAPMDefaultPPExempt-71276909", Int64.Type}, {"ERCAPMPPLevel-71276910", type text}, {"ERCSRShiptoEmail-71276911", type text}, {"ERCLastAPMStatementDT-71276912", type text}, {"ERCLastAPMStatementBy-71276913", type text}, {"ERCWOMRouteNo-71276914", type text}, {"ERCSitePointofContact-71276915", type text}, {"ERCDISRequirePicture-71276918", Int64.Type}, {"ERCDISRequireSignature-71276919", Int64.Type}, {"ERCEmailShipmentonPosting-71276920", Int64.Type}, {"ERCStatementErrorDateTime-71276921", type text}, {"ERCStatementErrorReason-71276922", type text}, {"ERCReminderEmailOption-71276923", type text}, {"timestamp-0", Int64.Type}, {"systemId-2000000000", type text}, {"SystemCreatedAt-2000000001", type datetime}, {"SystemCreatedBy-2000000002", type text}, {"SystemModifiedAt-2000000003", type datetime}, {"SystemModifiedBy-2000000004", type text}, {"$Company", type text}, {"$DeliveredDateTime", type datetime}, {"PhoneNo-9", type text}, {"MobilePhoneNo-5061", type text}, {"WTBARegionCode-87150", type text}, {"VATRegistrationNo-86", type text}})
in
  #"Changed column type";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Item27_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared Item27 = let
  Source = Excel.Workbook(Web.Contents("https://www.dropbox.com/scl/fi/4ce8rhjof5kjjoo1vndb1/Customer-and-Item.xlsx?rlkey=8n3qg2hntlii9r0yyp3avoe38&st=qiwunntm&dl=1"), null, true),
  #"Navigation 1" = Source{[Item = "Item27", Kind = "Sheet"]}[Data],
  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"No-1", type text}, {"No2-2", type text}, {"Description-3", type text}, {"SearchDescription-4", type text}, {"Description2-5", type text}, {"BaseUnitofMeasure-8", type text}, {"PriceUnitConversion-9", Int64.Type}, {"Type-10", type text}, {"InventoryPostingGroup-11", type text}, {"ShelfNo-12", type text}, {"ItemDiscGroup-14", type text}, {"AllowInvoiceDisc-15", Int64.Type}, {"StatisticsGroup-16", Int64.Type}, {"CommissionGroup-17", Int64.Type}, {"UnitPrice-18", Int64.Type}, {"PriceProfitCalculation-19", type text}, {"Profit-20", Int64.Type}, {"CostingMethod-21", type text}, {"UnitCost-22", type number}, {"StandardCost-24", Int64.Type}, {"LastDirectCost-25", type number}, {"IndirectCost-28", Int64.Type}, {"CostisAdjusted-29", Int64.Type}, {"AllowOnlineAdjustment-30", Int64.Type}, {"VendorNo-31", type text}, {"VendorItemNo-32", type text}, {"LeadTimeCalculation-33", type text}, {"ReorderPoint-34", Int64.Type}, {"MaximumInventory-35", Int64.Type}, {"ReorderQuantity-36", Int64.Type}, {"AlternativeItemNo-37", type text}, {"UnitListPrice-38", Int64.Type}, {"DutyDue-39", Int64.Type}, {"DutyCode-40", type text}, {"GrossWeight-41", Int64.Type}, {"NetWeight-42", Int64.Type}, {"UnitsperParcel-43", Int64.Type}, {"UnitVolume-44", type number}, {"Durability-45", type text}, {"FreightType-46", type text}, {"TariffNo-47", type text}, {"DutyUnitConversion-48", Int64.Type}, {"CountryRegionPurchasedCode-49", type text}, {"BudgetQuantity-50", Int64.Type}, {"BudgetedAmount-51", Int64.Type}, {"BudgetProfit-52", Int64.Type}, {"Blocked-54", Int64.Type}, {"BlockReason-56", type text}, {"LastDateTimeModified-61", type datetime}, {"LastDateModified-62", Int64.Type}, {"PriceIncludesVAT-87", Int64.Type}, {"VATBusPostingGrPrice-90", type text}, {"GenProdPostingGroup-91", type text}, {"CountryRegionofOriginCode-95", type text}, {"AutomaticExtTexts-96", Int64.Type}, {"NoSeries-97", type text}, {"TaxGroupCode-98", type text}, {"VATProdPostingGroup-99", type text}, {"Reserve-100", type text}, {"GlobalDimension1Code-105", type text}, {"GlobalDimension2Code-106", type text}, {"StockoutWarning-120", type text}, {"PreventNegativeInventory-121", type text}, {"VariantMandatoryifExists-122", type text}, {"ApplicationWkshUserID-521", type text}, {"AssemblyPolicy-910", type text}, {"GTIN-1217", type text}, {"DefaultDeferralTemplateCode-1700", type text}, {"LowLevelCode-5400", Int64.Type}, {"LotSize-5401", Int64.Type}, {"SerialNos-5402", type text}, {"LastUnitCostCalcDate-5403", type text}, {"RolledupMaterialCost-5404", Int64.Type}, {"RolledupCapacityCost-5405", Int64.Type}, {"Scrap-5407", Int64.Type}, {"RolledupMatNonInvtCost-5408", Int64.Type}, {"InventoryValueZero-5409", Int64.Type}, {"DiscreteOrderQuantity-5410", Int64.Type}, {"MinimumOrderQuantity-5411", Int64.Type}, {"MaximumOrderQuantity-5412", Int64.Type}, {"SafetyStockQuantity-5413", Int64.Type}, {"OrderMultiple-5414", Int64.Type}, {"SafetyLeadTime-5415", type text}, {"FlushingMethod-5417", type text}, {"ReplenishmentSystem-5419", type text}, {"RoundingPrecision-5422", Int64.Type}, {"SalesUnitofMeasure-5425", type text}, {"PurchUnitofMeasure-5426", type text}, {"TimeBucket-5428", type text}, {"ReorderingPolicy-5440", type text}, {"IncludeInventory-5441", Int64.Type}, {"ManufacturingPolicy-5442", type text}, {"ReschedulingPeriod-5443", type text}, {"LotAccumulationPeriod-5444", type text}, {"DampenerPeriod-5445", type text}, {"DampenerQuantity-5446", Int64.Type}, {"OverflowLevel-5447", Int64.Type}, {"ManufacturerCode-5701", type text}, {"ItemCategoryCode-5702", type text}, {"CreatedFromNonstockItem-5703", Int64.Type}, {"PurchasingCode-5711", type text}, {"ExcludedfromCostAdjustment-5801", Int64.Type}, {"ServiceItemGroup-5900", type text}, {"SustCertNo-6210", type text}, {"SustCertName-6211", type text}, {"GHGCredit-6212", Int64.Type}, {"CarbonCreditPerUOM-6213", Int64.Type}, {"DefaultSustAccount-6214", type text}, {"DefaultCO2Emission-6215", Int64.Type}, {"DefaultCH4Emission-6216", Int64.Type}, {"DefaultN2OEmission-6217", Int64.Type}, {"CO2eperUnit-6218", Int64.Type}, {"CO2eLastDateModified-6219", type text}, {"ItemTrackingCode-6500", type text}, {"LotNos-6501", type text}, {"ExpirationCalculation-6502", type text}, {"WarehouseClassCode-7300", type text}, {"SpecialEquipmentCode-7301", type text}, {"PutawayTemplateCode-7302", type text}, {"PutawayUnitofMeasureCode-7307", type text}, {"PhysInvtCountingPeriodCode-7380", type text}, {"LastCountingPeriodUpdate-7381", type text}, {"UseCrossDocking-7384", Int64.Type}, {"NextCountingStartDate-7385", type text}, {"NextCountingEndDate-7386", type text}, {"UnitofMeasureId-8001", type text}, {"TaxGroupId-8002", type text}, {"SalesBlocked-8003", Int64.Type}, {"PurchasingBlocked-8004", Int64.Type}, {"ItemCategoryId-8005", type text}, {"InventoryPostingGroupId-8006", type text}, {"GenProdPostingGroupId-8007", type text}, {"ServiceBlocked-8010", Int64.Type}, {"ProductionBlocked-8011", type text}, {"SubscriptionOption-8052", type text}, {"OverReceiptCode-8510", type text}, {"DutyClass-10004", type text}, {"HasSalesForecast-21850", Int64.Type}, {"SATItemClassification-27000", type text}, {"SATHazardousMaterial-27024", type text}, {"SATPackagingType-27025", type text}, {"SATMaterialType-27026", type text}, {"WCTEWPrestige-50000", Int64.Type}, {"WCINV04PurchaserCode-50010", type text}, {"WCINV08AgedInventory-50043", Int64.Type}, {"WCINV08ExpectedQtyfromVend-50044", Int64.Type}, {"WCINV08WHItemNo-50045", type text}, {"WCINV08NAforSalesreps-50046", Int64.Type}, {"WCINV08SuggestedRetailPrice-50047", Int64.Type}, {"WCAR06SalesCommissionable-50100", Int64.Type}, {"WCSAL04AllowSampleDiscount-50120", Int64.Type}, {"WCSAL04AllowPalletDiscount-50121", Int64.Type}, {"WCINV14ItemPortfolio-50150", type text}, {"WCINT02ExportedtoJFHB-50250", Int64.Type}, {"WCINT03ExportedtoMMK-50280", Int64.Type}, {"WCINV19DonotPrintonCat-50520", Int64.Type}, {"WCINT04PABlocked-50650", Int64.Type}, {"WCINT04SplitAllowed-50651", Int64.Type}, {"WTBAOriginRegionCode-87005", type text}, {"WTBASubRegionCode-87006", type text}, {"WTBAVarietalCode-87007", type text}, {"WTBACasePack-87010", Int64.Type}, {"WTBAItemClassificationCode-87014", type text}, {"WTBAAlcoholTypeCode-87015", type text}, {"WTBABottleSize-87020", type text}, {"WTBAWineColor-87025", type text}, {"WTBAContainerTypeCode-87028", type text}, {"WTBAAlcoholContent-87030", type number}, {"WTBAProof-87031", type number}, {"WTBAAppellationCode-87060", type text}, {"WTBAVegan-87062", Int64.Type}, {"WTBAOrganic-87063", Int64.Type}, {"WTBABiodynamic-87064", Int64.Type}, {"WTBAClosureTypeCode-87065", type text}, {"WTBALabelCode-87080", type text}, {"WTBASubAppellationCode-87085", type text}, {"WTBACasesperPalletLayer-87090", Int64.Type}, {"WTBALayersperPallet-87095", Int64.Type}, {"WTBACasesperPallet-87096", Int64.Type}, {"WTBAUnitCostCase-87110", type number}, {"WTBAUnitCostBottle-87111", type number}, {"WTBALastDirectCostCase-87115", type number}, {"WTBALastDirectCostBottle-87116", type number}, {"WTBAStandardCostCase-87120", Int64.Type}, {"WTBAStandardCostBottle-87121", Int64.Type}, {"WTBABrandNo-87150", type text}, {"WTBADoNotAllowSamples-87700", Int64.Type}, {"WTBAExclfromSampleBudget-87701", Int64.Type}, {"WTBASalesOrderReview-87850", Int64.Type}, {"WTUSSalesLimitation-88030", type text}, {"WTUSSalesLimAllocMethod-88035", type text}, {"WTUSCOLANo-88500", type text}, {"WTUSExciseTaxClass-88650", type text}, {"WTUSDonotPricePost-88800", Int64.Type}, {"WTIAAllocate-90100", Int64.Type}, {"WTIAFullAllocationRequired-90101", Int64.Type}, {"WTIAAllocationReservInt-90102", type text}, {"WTIAAllocationInheritCode-90103", type text}, {"WTIAAllocationisCurrent-90104", Int64.Type}, {"WTIAAllocJnlUnitofMeasure-90107", type text}, {"WTIALimitingQtyperSource-90130", Int64.Type}, {"WTIALimitingUnitType-90140", type text}, {"RoutingNo-99000750", type text}, {"ProductionBOMNo-99000751", type text}, {"SingleLevelMaterialCost-99000752", Int64.Type}, {"SingleLevelCapacityCost-99000753", Int64.Type}, {"SingleLevelSubcontrdCost-99000754", Int64.Type}, {"SingleLevelCapOvhdCost-99000755", Int64.Type}, {"SingleLevelMfgOvhdCost-99000756", Int64.Type}, {"OverheadRate-99000757", Int64.Type}, {"RolledupSubcontractedCost-99000758", Int64.Type}, {"RolledupMfgOvhdCost-99000759", Int64.Type}, {"RolledupCapOverheadCost-99000760", Int64.Type}, {"OrderTrackingPolicy-99000773", type text}, {"SingleLvlMatNonInvtCost-99000779", Int64.Type}, {"AllowWhseOverpick-99000780", Int64.Type}, {"Critical-99000875", Int64.Type}, {"CommonItemNo-99008500", type text}, {"timestamp-0", Int64.Type}, {"systemId-2000000000", type text}, {"SystemCreatedAt-2000000001", type datetime}, {"SystemCreatedBy-2000000002", type text}, {"SystemModifiedAt-2000000003", type datetime}, {"SystemModifiedBy-2000000004", type text}, {"$Company", type text}, {"$DeliveredDateTime", type datetime}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Changed column type", {{"WTBAVintageCode-87000", type text}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Changed column type 1", {{"LastTimeModified-63", type datetime}, {"LastDateModified-62", type date}})
in
  #"Changed column type 2";
shared Item27_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "2f1c0603-0152-47df-8538-a5b9c2fed106"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "6b9b268b-1bfc-4e19-9bea-11d7a6b8d89b"]}[Data],
  TableNavigation = Navigation_2{[Id = "Item27", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
shared Customer18_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "2f1c0603-0152-47df-8538-a5b9c2fed106"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "6b9b268b-1bfc-4e19-9bea-11d7a6b8d89b"]}[Data],
  TableNavigation = Navigation_2{[Id = "Customer18", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
